name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install dependencies
      run: |
        pip install pip==21.3.1
        pip install .
        sudo apt install git
        pip install git+git+https://github.com/OpenPecha/Collection
        
    - name: Test with pytest
      run: |
        pytest
    - name: Test Coverage
      run: |
        coverage run -m pytest
        coverage report -m
